/*Queries 01*/
SELECT JOB_ID, SUM(SALARY) AS "SUM SALARY"
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY "SUM SALARY" DESC;

/*Queries 02*/
SELECT ROUND(AVG(SALARY), 2)
FROM EMPLOYEES;

/*Queries 03*/
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES e
         INNER JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;

/*Queries 04*/
SELECT DEPARTMENT_NAME,
       POSTAL_CODE,
       CITY,
       STATE_PROVINCE,
       STREET_ADDRESS
FROM DEPARTMENTS
         INNER JOIN LOCATIONS l ON DEPARTMENTS.LOCATION_ID = l.LOCATION_ID;

/*Queries 05*/
SELECT DEPARTMENT_NAME,
       STREET_ADDRESS,
       POSTAL_CODE,
       CITY,
       STATE_PROVINCE,
       COUNTRY_NAME
FROM LOCATIONS
         INNER JOIN DEPARTMENTS d ON LOCATIONS.LOCATION_ID = d.LOCATION_ID
         INNER JOIN COUNTRIES c ON LOCATIONS.COUNTRY_ID = c.COUNTRY_ID;

/*Queries 06*/
SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS MANAGER,
       DEPARTMENT_NAME,
       STREET_ADDRESS,
       POSTAL_CODE,
       CITY,
       STATE_PROVINCE,
       COUNTRY_NAME
FROM DEPARTMENTS
         INNER JOIN LOCATIONS l ON DEPARTMENTS.LOCATION_ID = l.LOCATION_ID
         INNER JOIN COUNTRIES c ON l.COUNTRY_ID = c.COUNTRY_ID
         INNER JOIN EMPLOYEES e ON DEPARTMENTS.DEPARTMENT_ID = e.DEPARTMENT_ID
WHERE JOB_ID LIKE '%MAN';

/*Queries 07*/
SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS "Name", JOB_TITLE AS "JOB", SALARY, DEPARTMENT_NAME
FROM EMPLOYEES
         INNER JOIN JOBS j on EMPLOYEES.JOB_ID = j.JOB_ID
         INNER JOIN DEPARTMENTS d ON EMPLOYEES.DEPARTMENT_ID = d.DEPARTMENT_ID;

/*Queries 08*/
SELECT BOSS.EMPLOYEE_ID,
       CONCAT(BOSS.FIRST_NAME, ' ', BOSS.LAST_NAME)     AS "BOSS",
       WORKER.MANAGER_ID,
       CONCAT(WORKER.FIRST_NAME, ' ', WORKER.LAST_NAME) AS "WORKER"
FROM EMPLOYEES WORKER
         INNER JOIN EMPLOYEES BOSS ON WORKER.MANAGER_ID = BOSS.EMPLOYEE_ID
ORDER BY BOSS.EMPLOYEE_ID ASC;